version: '3'

services:
  study_d:
    build: .
    command: java -jar /home/service/target/study_d-1.0.jar
    container_name: study_d
    restart: unless-stopped
    ports:
      - "3333:3322"
    depends_on:
      - study_d_db
    environment:
      - EXAMPLE_ENVIRONMENT_VARIABLE=123456
      - POSTGRES_URL=study_d_db:5432/study_d

  study_d_db:
    image: postgres:11.14-alpine
    container_name: study_d_db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=study_d_adm
      - POSTGRES_DB=study_d